[Feature/#1] 기초 setting
TeamTalkable/ANDROID pull request #2
Opened 2024-05-19 06:10 UTC by youjin09222

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #1

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- [x] 패키지 분리
- [x] 디자인 시스템 - 컬러
- [x] 디자인 시스템 - 폰트

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
- 잘못된 부분이나 누락된 부분 있음 편하게 말해줘!

2024-05-19 16:24 UTC, sohyun127 requested changes
기초 세팅하느라 고생 너무 너무 많았어!!! 
리뷰 중에 궁금한거 있으면 물어보고!! P1 단계 리뷰 반영하면 Approve 하겠슴다

2024-05-19 16:24 UTC, sohyun127 commented on app/proguard-rules.pro
P1 : 프로가드 파일은 아직 안 쓰는 파일이니까 지워주셔도 됩니다!

2024-05-19 16:24 UTC, sohyun127 commented on app/src/androidTest/java/com/talkable/ExampleInstrumentedTest.kt
P1 : 테스트 파일도 지금 안 써서 지워주세요!

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/AndroidManifest.xml
> +        android:theme="@style/Theme.Talkable"
P1 : 서버 통신 대비해서 미리 추가해둡시다~!
```suggestion
        android:theme="@style/Theme.Talkable"
        android:usesCleartextTraffic="true"
```

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/AndroidManifest.xml
> +
P1 : 서버 통신 대비해서 미리 추가해둡시다~!
```suggestion
<uses-permission android:name="android.permission.INTERNET" />
```

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/java/com/talkable/core/base/BindingFragment.kt
> +        get() = requireNotNull(_binding) {
P2 : { } 내용 추가해주거나, 삭제해주세요-!
```suggestion
        get() = requireNotNull(_binding) {
        "binding object is not initialized"
```

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/AndroidManifest.xml
> +            android:exported="true">
P1 : 가로 모드 미리 막아둡시다~!
```suggestion
            android:exported="true"
            android:screenOrientation="portrait" >
```

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/java/com/talkable/data/ApiFactory.kt
> +            Log.d("Retrofit2", "CONNECTION INFO -> $message")
P2 :  요렇게 하면 릴리즈 배포할 때도 로그가 찍혀서 `if (BuildConfig.DEBUG)` 블럭 안에 넣어주셔야 합니다
사실 저는 android의 Log 클래스 위의 구축된 로깅 유틸리티 클래스인 Timber라는 녀석이 더 간단해서 Log 대신 애용합니다-! 제가 이부분은 Timber로 바꾸면서 디버깅 모드에서만 찍히도록 변경해둘게요!

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/res/values-night/themes.xml
> +    <style name="Base.Theme.Talkable" parent="Theme.Material3.DayNight.NoActionBar">
P1 : 다크 모드 미리 막아둡시다
```suggestion
    <style name="Base.Theme.Talkable" parent="Theme.Material3.Light.NoActionBar">
```

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/res/values/colors.xml
> +    <color name="font5">#F5F5F5</color>
P2 : 피그마랑 이름 통일 되어있는건 좋은데 저희는 위랑 통일성 있게 가죠?!
```suggestion
    <color name="font">#0F0F0F</color>
    <color name="font_2">#1F1F1F</color>
    <color name="font_3">#353535</color>
    <color name="font_4">#cccccc</color>
    <color name="font_5">#F5F5F5</color>
```

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/res/values/themes.xml
> +    <style name="Base.Theme.Talkable" parent="Theme.Material3.DayNight.NoActionBar">
P1 :
```suggestion
    <style name="Base.Theme.Talkable" parent="Theme.Material3.Light.NoActionBar">
```

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/res/values-night/themes.xml
> +        <!-- <item name="colorPrimary">@color/my_dark_primary</item> -->
P1 : 요기에도 미리 추가해두면 좋을 것 같아요!
```suggestion
       <!-- Primary brand color. -->
        <item name="colorPrimary">@color/main</item>
        <item name="colorOnPrimary">@color/white</item>
        <!-- Status bar color. -->
        <item name="android:statusBarColor">@android:color/transparent</item>
        <item name="android:windowLightStatusBar">true</item>
```

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/res/values/textAppearances.xml
> +        <item name="lineHeight">38dp</item>
P2 : lineHeight 피그마에 정의 안되어 있던데 어떤거 보고 값 넣으신건가요?!

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/res/xml/backup_rules.xml
P1 : 아직 안 쓰는 파일들 제거

2024-05-19 16:24 UTC, sohyun127 commented on app/src/main/res/xml/data_extraction_rules.xml
P1 : 아직 안 쓰는 파일들 제거

2024-05-19 16:24 UTC, sohyun127 commented on app/src/test/java/com/talkable/ExampleUnitTest.kt
P1 : 아직 안 쓰는 파일들 제거

2024-05-19 16:24 UTC, sohyun127 commented on app/build.gradle
P1 : 현재 Groovy DSL (Groovy 기반의 gradle)인데, 모두 Kotlin DSL 처럼 구현이 되어 있네요! gradle 부분은 제가 수정할게요! DSL이 뭔지 궁금하시면 나중에 한번 찾아봐도 좋을 것 같아요!

2024-05-19 16:24 UTC, sohyun127 commented on gradle/libs.versions.toml
comment : version catalog를 쓰셨군요?! 👍

2024-05-19 17:44 UTC, youjin09222 commented on app/src/main/java/com/talkable/data/ApiFactory.kt
> +            Log.d("Retrofit2", "CONNECTION INFO -> $message")
오 알려주셔서 감사합니다!

2024-05-19 17:47 UTC, youjin09222 commented on app/src/main/res/values/textAppearances.xml
> +        <item name="lineHeight">38dp</item>
어라 이거 학생 계정 인증 안됐을 때는 보였는데 지금은 안보이네요..?
일단 삭제해놓겠습니다!

2024-05-20 01:05 UTC, sohyun127 approved these changes
LGTM 👍 고생했어!!

2024-05-20 05:31 UTC, merged